### PR TITLE
Compat issues

### PR DESCRIPTION
**Pull request by tpoisot**
ignore the manifest and see what's up with CompatHelper

### CODE REVIEW

**Comment by tpoisot** [comment]
So, the CI test is running 1.3 - 1.5, but CompatHelper runs 1.2 -- maybe this is the problem?

**Comment by tpoisot** [comment]
I have also given `/test` its own project - which versions of Julia do you *need* to support?

**Comment by evadelmas** [comment]
> which versions of Julia do you _need_ to support?

[1.3.0 - 1.5.3]

**Comment by evadelmas** [comment]
Maybe that's another issue: 

> Your new version pull request does not meet the guidelines for auto-merging. Please make sure that you have read the General registry README. The following guidelines were not met:
> - The following dependencies do not have a [compat] entry that is upper-bounded and only includes a finite number of breaking releases: DiffEqCallbacks, OrdinaryDiffEq

**Review by evadelmas — APPROVED** [review]

**Pull request merged**
